### PR TITLE
Bumped to version 0.8.0

### PR DESCRIPTION
**Pull request by Wmbat**
Bumping the package version of magic_enum to the latest release of the original library

### CODE REVIEW

**Review by Klaim — APPROVED** [review]
Looks good to me - didn't try it though, but if it passes CI you're good to go.

**Comment by Wmbat** [comment]
There were some errors w.r.t to windows symlinks: https://ci.cppget.org/@a40e0cbb-0493-48d9-afeb-41d8676a4af4?builds=&pv=&tc=*&cf=&mn=&tg=&rs=error

so i'll have to work on it a bit more. I often get those problems, not sure why

**Comment by Klaim** [comment]
Looks like it's because you setup the symlinks with an absolute path, which is only valid on your computer (we can see `/home/wombat/...` ). When setting the symlinks, go in the directory where the symlink is and set it with a relative path (something like ` ln -s ../upstream/some/file file`.

Also, if ever you have directory symlinks, keep in mind that to support them on windows you need to list them in the ` .gitattributes`  file. It's annoying but maybe in the future `build2`  tools will help to do that automatically: https://github.com/build2/build2/issues/189

**Comment by Wmbat** [comment]
For some reason, two symlinks were added and i'm not sure why, but they're the ones that were causing problems.

https://ci.cppget.org/@92e29c3e-95e6-4520-945c-b9a8e9de9991?builds=&pv=&tc=*&cf=&mn=&tg=&rs=*

the CI has no failed builds now, so it should be all good & i'll merge it

**Pull request merged**
